# Generated by Django 6.0.2 on 2026-03-01 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa produktu')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena podstawowa')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa koloru')),
                ('hex_code', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Kod Hex (np. #FF0000)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/colors/', verbose_name='Zdjęcie wariantu')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dodatkowa cena')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='store.product')),
            ],
            options={
                'verbose_name': 'Kolor',
                'verbose_name_plural': 'Kolory',
            },
        ),
        migrations.CreateModel(
            name='SubOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa opcji')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dodatkowa cena')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.product')),
            ],
            options={
                'verbose_name': 'Podopcja',
                'verbose_name_plural': 'Podopcje',
            },
        ),
    ]
